services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./user_db/data:/docker-entrypoint-initdb.d

  api:
    depends_on:
      - db
    image: inable-auth
    container_name: inable-auth
    ports:
      - '80:3000'
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/inable

volumes:
  mysql_data:
    driver: local
